// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/collapse-options/AutoCollapse.tsx": () => import("../components/mockups/collapse-options/AutoCollapse.tsx"),
  "./components/mockups/collapse-options/DoneButton.tsx": () => import("../components/mockups/collapse-options/DoneButton.tsx"),
  "./components/mockups/collapse-options/SoftGate.tsx": () => import("../components/mockups/collapse-options/SoftGate.tsx"),
  "./components/mockups/product-card/ProductCard.tsx": () => import("../components/mockups/product-card/ProductCard.tsx"),
  "./components/mockups/streamlined-ui/Current.tsx": () => import("../components/mockups/streamlined-ui/Current.tsx"),
  "./components/mockups/streamlined-ui/Streamlined.tsx": () => import("../components/mockups/streamlined-ui/Streamlined.tsx")
};
