// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/product-card/ProductCard.tsx": () => import("../components/mockups/product-card/ProductCard.tsx")
};
